---
- name: aws s3 upload
  hosts: localhost
  become: true
  pre_task:
    - name: make directory
      file:
        path: ~/jar
        state: directory
        mode: 0644
    - name: copy jar file to localhost
      synchronize:
        src: ~/"{{ path_to_jar }}"
        dest: ~/jar
      delegate_to: 18.222.13.15
    
  roles:
    - ljemal.demos.awsupload
