---
- name: aws s3 upload
  hosts: all
  become: true
  pre_tasks:
    - name: copy file
      slurp:
        src: "{{ path_to_jar }}"
      register: jar
      delegate_to: localhost
  roles:
    - ljemal.demos.awsupload
