---
- name: Ansible test
  hosts: localhost
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
        key_name: sept
        instance_type: t2.micro
        image: ami-092b43193629811af
        region: us-east-2
        wait: yes
        group: Ansible
        count: 1
        vpc_subnet_id: default
        assign_public_ip: yes
