---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: sept
    instance_type: t2.micro
    security_group: default
    image: ami-092b43193629811af
    region: us-east-2
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-086194c049813830f
         assign_public_ip: yes
      register: ec2
