---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: sept
    instance_type: t2.micro
    security_group: default
    image: ami-092b43193629811af
    region: us-east-2
    instance_name: instance
  roles:
    - ljemal.demos.createec
  post_tasks:
    - name: Wait for system to become reachable over SSH
      ansible.builtin.wait_for_connection:
        timeout: 900
     
       
