- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        region: "{{ aws_region }}"
        state: absent
        filters:
          tag:Name: "{{ instance_name }}"
        register: aws_instance_destroy
