- name: Terminate instances
  hosts: localhost
  gather_facts: False
  vars:
    region: us-east-2
    instance_name: instance
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        region: "{{ region }}"
        state: absent
        instance_tags:
          Name: "{{ instance_name }}"
        register: aws_instance_destroy
