---
- name: wait
  hosts: all
  gather_facts: false
  tasks:
  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    ansible.builtin.wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 10
 
 
