---
- name: create bucket
  amazon.aws.s3_bucket:
    name: mybucket
    state: present
  delegate_to: localhost
- name: upload file to s3 bucket
  amazon.aws.aws_s3:
    bucket: mybucket
    object: compile.jar
    content_base64: "{{ jar['content'] }}"
    mode: put
  delegate_to: localhost
  
       
