---
- name: make directory
  file:
    path: ~/jar
    state: directory
    mode: 0644
- name: copy jar file to localhost
  synchronize:
    src: ~/"{{ path_to_jar }}"
    dest: ~/jar
  delegate_to: 18.222.13.15
- name: upload file to s3 bucket
  amazon.aws.aws_s3:
    bucket: mybucket
    object: compile.jar
    src: ~/jar/*
    mode: put
       
