---
- name: copy file from remote directory
  slurp:
    src: "{{ path_to_jar }}"
  register: jar
- name: upload file to s3 bucket
  amazon.aws.aws_s3:
    bucket: mybucket
    object: compile.jar
    src: jar
    mode: put
  delegate_to: localhost
  
       
