---
- name: copy file
  slurp:
    src: "{{ path_to_jar }}"
  register: jar
- name: upload file to s3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: "{{ object }}"
    content_base64: "bucket_source"
    region: "{{ region }}"
    mode: put
  delegate_to: localhost

       
