---

- name: upload file to s3 bucket
  amazon.aws.aws_s3:
    bucket: bucketforcomp
    object: "{{ jar['content']}}"
    content_base64: "{{ jar['content'] }}"
    region: 'us-east-2'
    mode: put
  delegate_to: localhost
  become: true
  
       
