---
- name: "Compile {{ app_name }}"
  hosts: all
  become: false
  vars_files:
    - ci_vars.yml

  tasks:
    - name: Create workspace directory
      ansible.builtin.file:
        path: "{{ directory }}/go/src"
        state: directory
        mode: 0755

    - name: Ensure clean app workspace
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: absent

    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ app_repo_url }}"
        dest: "{{ app_path }}"
        version: "{{ app_repo_branch }}"
        refspec: "{{ app_repo_refspec }}"
      register: _app_repo
