---
- name: aws s3 upload
  hosts: all
  become: true
  tasks:
    - name: list source and save to register
      shell: "ls -lrt /path/to/jar file"
      register: dirlist
   
    - name: save output to content var
      set_fact:
        content: "{{ dirlist.stdout_lines}}"
      when: dirlist.changed

    - name: display before writing
      debug: msg="{{ content }}"

    - name: upload file to s3 bucket
      amazon.aws.aws_s3:
        profile:
        bucket:
        mode: 
        object: ""
        content: ""
      register: putresult
