---
- name: aws s3 upload
  hosts: all
  become: true
  collections:
    - amazon.aws
  tasks:
    
    - name: upload file to s3 bucket
      amazon.aws.aws_s3:
        bucket: mybucket
        object: compile.jar
        src: ~/"{{ path_to_jar }}"
        mode: put
       
