---
- name: Clone repo
  hosts: all
  become: false
  tasks:
    - name: create workspace dir
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: 0755
    - name: ensure clean app workspace
      file:
        path: "{{ app_directory }}"
        state: absent
    - name: install git
      yum:
        name: git
        state: present
        update_cache: true
    - name: clone repo
      git:
        repo: "{{ repo }}" 
        dest: "{{ app_directory }}"
        version: "{{ branch }}"
      register: app_repo
