---
- name: Clone repo
  hosts: all
  become: false
  tasks:
    - name: create workspace dir
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: 0755
    - name: ensure clean app workspace
      file:
        path: "{{ app_path }}"
        state: absent
    - name: clone repo
      git:
        repo: "{{ repo }}" //repo for src (this repo)
        dest: "{{ app_path }}"
        version: "{{ branch }}"
        refspec: "{{ refspec }}"
      register: app_repo
